name: cmda-notebooks
channels:
  - pyviz
  - conda-forge
dependencies:
  - python=3.7
  - xarray
  - pandas=1.0.5
  - matplotlib-base
  - cartopy
  - hvplot
  - requests
  - geoviews
  - panel
  - beautifulsoup4
  -jupyterlab
