name: cmda-notebooks
channels:
  - conda-forge
dependencies:
  - python=3.10
  - netCDF4
  - xarray
  - h5netcdf
  - gcsfs
  - s3fs
  - basemap
  - palettable
  - cmocean
  - geopandas
  - pyogrio
  - statsmodels
  - matplotlib-base
  - cartopy
  - rasterio
  - rioxarray
  - requests
