name: cmda-notebooks
channels:
  - conda-forge
dependencies:
  - python=3.10
  - netCDF4
  - xarray
  - rioxarray
  - tqdm
  - h5netcdf
  - gcsfs
  - s3fs
  - basemap
  - palettable
  - cmocean
  - geopandas
  - statsmodels
  - matplotlib-base
  - cartopy
  - requests
  - numba
  - sqlite>=3.46.0
