name: cmda-notebooks
channels:
  - pyviz
  - conda-forge
dependencies:
  - python=3.8
  - xarray=0.17.0
  - h5netcdf
  - gcsfs
  - s3fs
  - intake-esm
  - bcdp
  - statsmodels
  - pandas=1.0.5
  - matplotlib-base=3.4.1
  - nc-time-axis
  - cartopy=0.18.0
  - hvplot=0.7.1
  - rasterio
  - rioxarray
  - requests
  - geoviews=1.9.1
  - panel=0.11.3
  - beautifulsoup4=4.9.3
  - jupyterlab=3.0.7
  - numpy=1.20.2
  - param=1.10.1
  - holoviews=1.14.3
  - jinja2=2
